name: style

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
