name: style

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: read

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dskkato/ros2-cuda-ipc:0.0.1
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
